openapi: 3.0.1
info:
  title: My APIs Spec
  contact:
    email: d19921207@gmail.com
  version: 0.1.0
servers:
  # TODO: add API Gateway endpoint
  - url: http://localhost:3000
tags:
  - name: config
    description: config
  - name: streamer
    description: streamer
  - name: monitoring
    description: monitoring of streamer
paths:
  /config:
    get:
      tags:
        - config
      summary: get config
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Config"
  /monitorings:
    delete:
      tags:
        - monitoring
      summary: unmonitor all (for debug)
      responses:
        204:
          description: successful operation
  /streamers:
    get:
      tags:
        - streamer
      summary: search streamers
      parameters:
        - name: id
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/StreamerId"
            minLength: 1
            maxLength: 100
        - name: name
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/StreamerName"
            minLength: 1
            maxLength: 100
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamerList'
  /streamers/{streamerId}/monitoring:
    put:
      tags:
        - streamer
        - monitoring
      summary: get monitored
      parameters:
        - name: streamerId
          in: path
          schema:
            $ref: "#/components/schemas/StreamerId"
          required: true
      responses:
        204:
          description: successful operation
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    Config:
      type: object
      properties:
        pusher:
          type: object
          properties:
            key:
              type: string
            appId:
              type: string
            cluster:
              type: string
              example: "ap3"
            channel:
              type: string
              example: "my-channel"
            event:
              type: string
              example: "my-event"
          required:
            - key
            - appId
            - cluster
            - channel
            - event
      required:
        - pusher
    Streamer:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/StreamerId"
        name:
          $ref: "#/components/schemas/StreamerName"
        is_live:
          type: boolean
      required:
        - id
        - name
        - is_live
    StreamerId:
      type: string
      example: "12345678"
    StreamerName:
      type: string
      example: "wand_ota4"
    StreamerList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Streamer"
      required:
        - data

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []
