/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/config": {
    get: {
      responses: {
        /** successful operation */
        200: {
          content: {
            "application/json": components["schemas"]["Config"];
          };
        };
      };
    };
  };
  "/monitorings": {
    delete: {
      responses: {
        /** successful operation */
        204: never;
      };
    };
  };
  "/streamers": {
    get: {
      parameters: {
        query: {
          id?: components["schemas"]["StreamerId"][];
          name?: components["schemas"]["StreamerName"][];
        };
      };
      responses: {
        /** successful operation */
        200: {
          content: {
            "application/json": components["schemas"]["StreamerList"];
          };
        };
      };
    };
  };
  "/streamers/{streamerId}/monitoring": {
    put: {
      parameters: {
        path: {
          streamerId: components["schemas"]["StreamerId"];
        };
      };
      responses: {
        /** successful operation */
        204: {
          content: {
            "application/json": { [key: string]: any };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Config: {
      pusher_key?: string;
    } & { [key: string]: any };
    Streamer: {
      id: components["schemas"]["StreamerId"];
      name: components["schemas"]["StreamerName"];
      is_live: boolean;
    } & { [key: string]: any };
    StreamerId: string;
    StreamerName: string;
    StreamerList: {
      data: components["schemas"]["Streamer"][];
    } & { [key: string]: any };
  };
}

export interface operations {}
