/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/eventsub/subscriptions": {
    get: {
      responses: {
        /** successful operation */
        200: {
          content: {
            "application/json": components["schemas"]["SubscriptionPagination"];
          };
        };
      };
    };
    post: {
      responses: {
        /** successful operation */
        200: {
          content: {
            "application/json": components["schemas"]["SubscriptionPagination"];
          };
        };
      };
      /** Subscription */
      requestBody: {
        content: {
          "application/json": components["schemas"]["SubscriptionToPost"];
        };
      };
    };
    delete: {
      parameters: {
        query: {
          id?: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          content: {
            "application/json": { [key: string]: any };
          };
        };
      };
    };
  };
  "/example/callback-handshake": {
    post: {
      responses: {
        /** Challenge Response */
        200: {
          headers: {};
          content: {
            "text/plain": components["schemas"]["VerificationResponseBody"];
          };
        };
      };
      /** Challenge */
      requestBody: {
        content: {
          "application/json": components["schemas"]["VerificationRequestBody"];
        };
      };
    };
  };
  "/example/callback-notification": {
    post: {
      responses: {
        /** successful operation */
        200: {
          headers: {};
          content: {
            "application/json": { [key: string]: any };
          };
        };
      };
      /** Notification */
      requestBody: {
        content: {
          "application/json": components["schemas"]["Notification"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Condition: {
      broadcaster_user_id?: string;
    } & { [key: string]: any };
    TransportCommon: {
      method: "webhook";
      /** valid https URI */
      callback: string;
    } & { [key: string]: any };
    TransportToGet: components["schemas"]["TransportCommon"];
    TransportToPost: components["schemas"]["TransportCommon"] &
      ({
        /** shared secret for HMAC-SHA256 */
        secret: string;
      } & { [key: string]: any }) & { [key: string]: any };
    SubscriptionType: "channel.follow" | "stream.online" | "stream.offline";
    SubscriptionCommon: {
      type: components["schemas"]["SubscriptionType"];
      version: string;
      condition: components["schemas"]["Condition"];
    } & { [key: string]: any };
    SubscriptionToPost: components["schemas"]["SubscriptionCommon"] &
      ({
        transport: components["schemas"]["TransportToPost"];
      } & { [key: string]: any }) & { [key: string]: any };
    SubscriptionToGet: components["schemas"]["SubscriptionCommon"] &
      ({
        id: string;
        status:
          | "enabled"
          | "webhook_callback_verification_pending"
          | "webhook_callback_verification_failed"
          | "notification_failures_exceeded"
          | "authorization_revoked"
          | "user_removed";
        cost: number;
        transport: components["schemas"]["TransportToGet"];
        created_at: string;
      } & { [key: string]: any }) & { [key: string]: any };
    SubscriptionPagination: components["schemas"]["Pagination"] &
      ({
        data: components["schemas"]["SubscriptionToGet"][];
      } & { [key: string]: any }) & { [key: string]: any };
    Challenge: string;
    VerificationRequestBody: {
      challenge: components["schemas"]["Challenge"];
      subscription: components["schemas"]["SubscriptionToGet"];
    } & { [key: string]: any };
    VerificationResponseBody: components["schemas"]["Challenge"];
    Notification: {
      subscription: components["schemas"]["SubscriptionToGet"];
      event: components["schemas"]["Event"];
    } & { [key: string]: any };
    CallbackRequestBody: (Partial<
      components["schemas"]["VerificationRequestBody"]
    > &
      Partial<components["schemas"]["Notification"]>) & { [key: string]: any };
    Event: (Partial<components["schemas"]["EventChannelFollow"]> &
      Partial<components["schemas"]["EventStreamOnline"]> &
      Partial<components["schemas"]["EventStreamOffline"]>) & {
      [key: string]: any;
    };
    EventChannelFollow: {
      user_id: string;
      user_login: string;
      user_name: string;
      broadcaster_user_id: string;
      broadcaster_user_login: string;
      broadcaster_user_name: string;
      followed_at: string;
    } & { [key: string]: any };
    EventStreamOnline: {
      /** the id of the stream */
      id: string;
      broadcaster_user_id: string;
      broadcaster_user_login: string;
      broadcaster_user_name: string;
      type: "live" | "playlist" | "watch_party" | "premiere" | "rerun";
      started_at: string;
    } & { [key: string]: any };
    EventStreamOffline: {
      broadcaster_user_id: string;
      broadcaster_user_login: string;
      broadcaster_user_name: string;
    } & { [key: string]: any };
    Pagination: {
      total: number;
      total_cost: number;
      max_total_cost: number;
      limit: number;
    } & { [key: string]: any };
  };
  headers: {
    "Twitch-Eventsub-Message-Id"?: string;
    "Twitch-Eventsub-Message-Timestamp"?: string;
    /** HMAC-SHA256 signature of Id + Timestamp + Body */
    "Twitch-Eventsub-Message-Signature"?: string;
  };
}

export interface operations {}
